// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LNAxwh_NRi5qd0o2dpbdxrMjYQCJg5o',
    appId: '1:464870451279:web:fb48eaa9e367626927223a',
    messagingSenderId: '464870451279',
    projectId: 'todoist-5ac20',
    authDomain: 'todoist-5ac20.firebaseapp.com',
    storageBucket: 'todoist-5ac20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq73fWjvCrgX19t_YQyFN-ElQohQL5JCo',
    appId: '1:464870451279:android:f7c2171db22d512f27223a',
    messagingSenderId: '464870451279',
    projectId: 'todoist-5ac20',
    storageBucket: 'todoist-5ac20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFubCCpL8jN4avD6lOqp3mHhMUGn6Edl4',
    appId: '1:464870451279:ios:b71a148befa5a1b527223a',
    messagingSenderId: '464870451279',
    projectId: 'todoist-5ac20',
    storageBucket: 'todoist-5ac20.firebasestorage.app',
    iosBundleId: 'com.example.todoist',
  );
}
